VERSION     := 1.0.0
COMMIT      := `git rev-parse HEAD`
DATE        := `date +%FT%T%z`
BUILD_FLAGS := "-X=main.appVersion=$(VERSION) -X=main.appCommit=$(COMMIT) -X=main.appBuilt=$(DATE)"
BUILD_DIR	:= "build"
APPNAME		:= "{{.AppName}}"

.PHONY: build

build:
	@echo "Compiling for DEV..."
	@go clean && go build -ldflags ${BUILD_FLAGS} -o ${BUILD_DIR}/${APPNAME}
	@echo "Build done!"
	@cd ${BUILD_DIR} && ./${APPNAME}

prod:
	@echo "Compiling for PROD..."
	@cd web/app && npm ci && npm run build && cd ../..
	@cd web/admin && npm ci && npm run build && cd ../..
	@rm -rf assets/web && mkdir assets/web && mv web/app/dist assets/web/app && mv web/admin/dist assets/web/admin
	@go clean && go generate && env GOOS=linux GOARCH=amd64 go build -ldflags ${BUILD_FLAGS} -o ${BUILD_DIR}/${APPNAME}
	@echo "Build done!"