VERSION     := 1.0.0
COMMIT      := `git rev-parse HEAD`
DATE        := `date +%FT%T%z`
BUILD_FLAGS := "-X=main.appVersion=$(VERSION) -X=main.appCommit=$(COMMIT) -X=main.appBuilt=$(DATE)"
BUILD_DIR	:= "build"
PROJECT		:= "{{.AppName}}"

.PHONY: build

build:
	@echo "Compiling for DEV..."
	@go clean && go build -ldflags ${BUILD_FLAGS} -o ${BUILD_DIR}/${PROJECT}
	@echo "Done!"

prod:
	@echo "Compiling for PROD ..."
	@go clean && go generate && env GOOS=linux GOARCH=amd64 go build -ldflags ${BUILD_FLAGS} -o ${BUILD_DIR}/${PROJECT}
	@echo "Compressing into tar.gz ..."
	@tar -czf ${BUILD_DIR}/${PROJECT}-`date +%FT%T`.tar.gz ${BUILD_DIR}/${PROJECT}
	@rm ${BUILD_DIR}/${PROJECT}
	@echo "Done!"